# permissions for end users to view kubescapevalidators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubescapevalidator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validator-plugin-kubescape
    app.kubernetes.io/part-of: validator-plugin-kubescape
    app.kubernetes.io/managed-by: kustomize
  name: kubescapevalidator-viewer-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - kubescapevalidators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - kubescapevalidators/status
  verbs:
  - get
